// Generated by `node tools/audiorender.mjs --calibrate` — do not edit by hand.
// Loudness calibration: gain per cue and the loudness it measured at that gain (see loudness.js).
export const CAL = {
 "fp": {
  "music": "1rf4pvc",
  "sfx": "9kju1p",
  "amb": "hutyqt"
 },
 "music": {
  "camp": {
   "gain": 1.518,
   "lufs": -18,
   "target": -18,
   "fp": "15pxq6v"
  },
  "combat": {
   "gain": 0.933,
   "lufs": -16.5,
   "target": -16.5,
   "sections": {
    "A": -0.7,
    "C": 1.7,
    "D": 1.6,
    "A2": -1.7,
    "B": -0.9
   },
   "curve": [
    [
     0.2,
     -18.9
    ],
    [
     0.3,
     -18.6
    ],
    [
     0.45,
     -16
    ],
    [
     0.6,
     -14.8
    ],
    [
     0.75,
     -9.9
    ],
    [
     0.9,
     -9.1
    ],
    [
     1,
     -9.1
    ]
   ],
   "fp": "1kdtouk",
   "check": {
    "1": -12.2,
    "0.3": -16.6,
    "0.5": -16.4,
    "0.8": -13.5
   }
  },
  "crypt": {
   "gain": 2.2887,
   "lufs": -18.1,
   "target": -18,
   "sections": {
    "v0": 1.2,
    "v3": -2.1,
    "v1": 3.1,
    "v2": -2.3
   },
   "fp": "j2l8s6"
  },
  "danger": {
   "gain": 1.2418,
   "lufs": -16.2,
   "target": -16,
   "fp": "12wi6qa"
  },
  "defeat": {
   "gain": 1.0541,
   "lufs": -19.5,
   "target": -19.5,
   "fp": "a9tzxp"
  },
  "discovery": {
   "gain": 0.9508,
   "lufs": -17,
   "target": -17,
   "fp": "sv4kn5"
  },
  "dungeon": {
   "gain": 1.4386,
   "lufs": -18.7,
   "target": -18.5,
   "sections": {
    "v0": -2.5,
    "v3": 3,
    "v1": -2.5,
    "v2": 2
   },
   "fp": "u3sdkg"
  },
  "encounter": {
   "gain": 1.5245,
   "lufs": -17.7,
   "target": -17.5,
   "sections": {
    "standoff": -0.9,
    "stalk": 2,
    "heartbeat": -1.1
   },
   "fp": "bkboi4"
  },
  "fallen": {
   "gain": 2.2674,
   "lufs": -18.2,
   "target": -18,
   "fp": "2220ey"
  },
  "intro": {
   "gain": 1.1012,
   "lufs": -18.5,
   "target": -18.5,
   "fp": "icddfq"
  },
  "levelup": {
   "gain": 1.1293,
   "lufs": -16,
   "target": -16,
   "fp": "7vhpal"
  },
  "quest": {
   "gain": 1.251,
   "lufs": -17,
   "target": -17,
   "fp": "xo7b64"
  },
  "ruins": {
   "gain": 1.5762,
   "lufs": -18.2,
   "target": -18,
   "sections": {
    "v0": -1.2,
    "v3": 3.3,
    "v1": -1.7,
    "v2": -0.3
   },
   "fp": "1nd6qpq"
  },
  "tavern": {
   "gain": 1.3582,
   "lufs": -17.1,
   "target": -17,
   "sections": {
    "set": -2.2,
    "air": 2.2
   },
   "fp": "nkqeu4"
  },
  "title": {
   "gain": 0.9088,
   "lufs": -16.9,
   "target": -17,
   "fp": "gt0nih"
  },
  "town": {
   "gain": 1.7372,
   "lufs": -17.1,
   "target": -17,
   "sections": {
    "set": -2,
    "air": 2
   },
   "fp": "n3b6x4"
  },
  "victory": {
   "gain": 0.6472,
   "lufs": -16,
   "target": -16,
   "fp": "1ys8g5e"
  },
  "wilds": {
   "gain": 1.3876,
   "lufs": -18,
   "target": -18,
   "sections": {
    "v0": -1.8,
    "v3": -2,
    "v1": -1.5,
    "v2": 5.3
   },
   "fp": "yfz8vl"
  }
 },
 "amb": {
  "camp": {
   "gain": 5.2729,
   "lufs": -27,
   "target": -27
  },
  "camp_in": {
   "gain": 4.6784,
   "lufs": -27,
   "target": -27
  },
  "camp_night": {
   "gain": 5.1449,
   "lufs": -27,
   "target": -27
  },
  "combat_in": {
   "gain": 5.0251,
   "lufs": -27,
   "target": -27
  },
  "combat_out": {
   "gain": 5.6957,
   "lufs": -27,
   "target": -27
  },
  "crypt": {
   "gain": 3.963,
   "lufs": -27,
   "target": -27
  },
  "crypt_night": {
   "gain": 4.5956,
   "lufs": -27,
   "target": -27
  },
  "dungeon": {
   "gain": 3.6489,
   "lufs": -27,
   "target": -27
  },
  "interior": {
   "gain": 9.4005,
   "lufs": -27,
   "target": -27
  },
  "ruins": {
   "gain": 3.2951,
   "lufs": -27,
   "target": -27
  },
  "ruins_night": {
   "gain": 3.6086,
   "lufs": -27,
   "target": -27
  },
  "title": {
   "gain": 2.5934,
   "lufs": -27,
   "target": -27
  },
  "town": {
   "gain": 5.0076,
   "lufs": -27,
   "target": -27
  },
  "town_night": {
   "gain": 4.953,
   "lufs": -27,
   "target": -27
  },
  "wilds": {
   "gain": 4.2426,
   "lufs": -27,
   "target": -27
  },
  "wilds_night": {
   "gain": 4.679,
   "lufs": -27,
   "target": -27
  }
 },
 "sfx": {
  "arrow_hit": {
   "gain": 3.7983,
   "m": -19.9,
   "target": -18.5,
   "peak": -2.9
  },
  "arrow_in": {
   "gain": 16,
   "m": -20.6,
   "target": -20,
   "peak": -8.5
  },
  "bite": {
   "gain": 3.1793,
   "m": -18.8,
   "target": -18.5,
   "peak": -3.9
  },
  "block": {
   "gain": 0.8996,
   "m": -18.2,
   "target": -18.5,
   "peak": -4.2
  },
  "bow": {
   "gain": 2.5047,
   "m": -20.1,
   "target": -20,
   "peak": -6.8
  },
  "bump": {
   "gain": 3.4748,
   "m": -23.5,
   "target": -23,
   "peak": -14.4
  },
  "cancel": {
   "gain": 3.3868,
   "m": -25,
   "target": -25,
   "peak": -13.1
  },
  "chest": {
   "gain": 1.5415,
   "m": -21,
   "target": -21,
   "peak": -8.7
  },
  "claw": {
   "gain": 2.1706,
   "m": -18.6,
   "target": -18.5,
   "peak": -5.8
  },
  "click": {
   "gain": 4.8631,
   "m": -27.1,
   "target": -27,
   "peak": -6.4
  },
  "close": {
   "gain": 7.4128,
   "m": -27,
   "target": -27,
   "peak": -8.4
  },
  "coins": {
   "gain": 2.2599,
   "m": -22.5,
   "target": -22.5,
   "peak": -11.2
  },
  "confirm": {
   "gain": 1.6457,
   "m": -25,
   "target": -25,
   "peak": -13.3
  },
  "crit": {
   "gain": 2.0042,
   "m": -15.7,
   "target": -15,
   "peak": -2.8
  },
  "death": {
   "gain": 1.4674,
   "m": -20.1,
   "target": -20,
   "peak": -6.3
  },
  "dodge": {
   "gain": 3.057,
   "m": -21,
   "target": -21,
   "peak": -9.6
  },
  "door": {
   "gain": 1.2102,
   "m": -21.4,
   "target": -21,
   "peak": -3.1
  },
  "door_close": {
   "gain": 0.9312,
   "m": -20.8,
   "target": -21,
   "peak": -3.1
  },
  "door_locked": {
   "gain": 0.7898,
   "m": -20.9,
   "target": -21,
   "peak": -5.7
  },
  "door_secret": {
   "gain": 1.3301,
   "m": -21,
   "target": -21,
   "peak": -10.6
  },
  "equip": {
   "gain": 4.6678,
   "m": -22.5,
   "target": -22.5,
   "peak": -7.9
  },
  "error": {
   "gain": 5.0551,
   "m": -25,
   "target": -25,
   "peak": -12.6
  },
  "focus": {
   "gain": 14.094,
   "m": -30,
   "target": -30,
   "peak": -10.4
  },
  "footstep": {
   "gain": 8.9946,
   "m": -26.4,
   "target": -26,
   "peak": -11.3
  },
  "heal": {
   "gain": 1.1863,
   "m": -20,
   "target": -20,
   "peak": -10.9
  },
  "hit": {
   "gain": 3.6412,
   "m": -18.7,
   "target": -17.5,
   "peak": -2.8
  },
  "hit_armor": {
   "gain": 1,
   "m": -17.7,
   "target": -17.5,
   "peak": -4.6
  },
  "hit_bone": {
   "gain": 3.3784,
   "m": -17.8,
   "target": -17.5,
   "peak": -3.3
  },
  "hover": {
   "gain": 16,
   "m": -31,
   "target": -30,
   "peak": -13.9
  },
  "levelup": {
   "gain": 0.8614,
   "m": -19,
   "target": -19,
   "peak": -10.3
  },
  "map": {
   "gain": 5.8842,
   "m": -27,
   "target": -27,
   "peak": -16.1
  },
  "miss": {
   "gain": 2.6104,
   "m": -21,
   "target": -21,
   "peak": -9.4
  },
  "omen": {
   "gain": 3.4009,
   "m": -21,
   "target": -21,
   "peak": -8.6
  },
  "open": {
   "gain": 7.0156,
   "m": -27,
   "target": -27,
   "peak": -11.6
  },
  "page": {
   "gain": 9.0307,
   "m": -27,
   "target": -27,
   "peak": -10.9
  },
  "parry": {
   "gain": 0.7839,
   "m": -17.5,
   "target": -17.5,
   "peak": -4.7
  },
  "pass_through": {
   "gain": 1.4815,
   "m": -21,
   "target": -21,
   "peak": -11.2
  },
  "potion": {
   "gain": 3.8614,
   "m": -22.5,
   "target": -22.5,
   "peak": -9.8
  },
  "ready": {
   "gain": 16,
   "m": -28,
   "target": -27,
   "peak": -12.4
  },
  "save": {
   "gain": 1.4937,
   "m": -25,
   "target": -25,
   "peak": -18.3
  },
  "shield": {
   "gain": 2.8407,
   "m": -20,
   "target": -18.5,
   "peak": -2.9
  },
  "sparkle": {
   "gain": 1.7927,
   "m": -25,
   "target": -25,
   "peak": -18.7
  },
  "spell": {
   "gain": 1.6231,
   "m": -20,
   "target": -20,
   "peak": -11
  },
  "spell_cloud": {
   "gain": 1.62,
   "m": -18.5,
   "target": -18.5,
   "peak": -7.4
  },
  "spell_cone": {
   "gain": 0.6865,
   "m": -16.4,
   "target": -16.5,
   "peak": -9.9
  },
  "spell_curse": {
   "gain": 3.0322,
   "m": -18.5,
   "target": -18.5,
   "peak": -6.8
  },
  "spell_fire": {
   "gain": 0.6428,
   "m": -14.3,
   "target": -14.5,
   "peak": -3.3
  },
  "spell_fizzle": {
   "gain": 6.0848,
   "m": -23,
   "target": -23,
   "peak": -9.1
  },
  "spell_heal": {
   "gain": 1.1863,
   "m": -20,
   "target": -20,
   "peak": -10.9
  },
  "spell_holy": {
   "gain": 0.7112,
   "m": -18.5,
   "target": -18.5,
   "peak": -10.7
  },
  "spell_lightning": {
   "gain": 1.1254,
   "m": -14.9,
   "target": -14.5,
   "peak": -2.7
  },
  "spell_mind": {
   "gain": 2.2988,
   "m": -20,
   "target": -20,
   "peak": -12.3
  },
  "spell_missile": {
   "gain": 5.4187,
   "m": -18.7,
   "target": -18.5,
   "peak": -2.4
  },
  "spell_shock": {
   "gain": 2.4936,
   "m": -19.5,
   "target": -18.5,
   "peak": -2.6
  },
  "spell_sleep": {
   "gain": 1.7415,
   "m": -20,
   "target": -20,
   "peak": -12.7
  },
  "spell_turn": {
   "gain": 0.3365,
   "m": -16.5,
   "target": -16.5,
   "peak": -8.3
  },
  "spell_ward": {
   "gain": 2.3123,
   "m": -20,
   "target": -20,
   "peak": -10.6
  },
  "splash": {
   "gain": 3.016,
   "m": -23,
   "target": -23,
   "peak": -8.6
  },
  "step_cobble": {
   "gain": 2.1945,
   "m": -26.1,
   "target": -26,
   "peak": -11.1
  },
  "step_dirt": {
   "gain": 4.7301,
   "m": -26.2,
   "target": -26,
   "peak": -11.3
  },
  "step_grass": {
   "gain": 2.3292,
   "m": -26.2,
   "target": -26,
   "peak": -13.7
  },
  "step_gravel": {
   "gain": 2.5605,
   "m": -26.4,
   "target": -26,
   "peak": -11.5
  },
  "step_stone": {
   "gain": 5.1244,
   "m": -26.2,
   "target": -26,
   "peak": -10.8
  },
  "step_water": {
   "gain": 1.5137,
   "m": -26.1,
   "target": -26,
   "peak": -14.3
  },
  "step_wood": {
   "gain": 1,
   "m": -26.2,
   "target": -26,
   "peak": -12.2
  },
  "swing": {
   "gain": 2.453,
   "m": -21,
   "target": -21,
   "peak": -10
  },
  "trap": {
   "gain": 0.4999,
   "m": -21,
   "target": -21,
   "peak": -6
  },
  "turn": {
   "gain": 7.6096,
   "m": -29,
   "target": -29,
   "peak": -13.6
  },
  "vox_dragon": {
   "gain": 0.5158,
   "m": -14,
   "target": -14,
   "peak": -6.9
  },
  "vox_dragon_die": {
   "gain": 0.4683,
   "m": -13.8,
   "target": -14,
   "peak": -7.7
  },
  "vox_frog": {
   "gain": 1.4087,
   "m": -19.5,
   "target": -19.5,
   "peak": -7.8
  },
  "vox_frog_die": {
   "gain": 2.1787,
   "m": -18.6,
   "target": -18.5,
   "peak": -4.3
  },
  "vox_ghost": {
   "gain": 3.2839,
   "m": -21,
   "target": -21,
   "peak": -13.2
  },
  "vox_ghost_die": {
   "gain": 4.4871,
   "m": -18.5,
   "target": -18.5,
   "peak": -11.6
  },
  "vox_giant": {
   "gain": 0.4009,
   "m": -16.2,
   "target": -16.5,
   "peak": -11.8
  },
  "vox_giant_die": {
   "gain": 0.3305,
   "m": -16.5,
   "target": -16.5,
   "peak": -9.6
  },
  "vox_gnoll": {
   "gain": 1,
   "m": -19.6,
   "target": -19.5,
   "peak": -10.7
  },
  "vox_gnoll_die": {
   "gain": 0.8723,
   "m": -18.5,
   "target": -18.5,
   "peak": -10
  },
  "vox_goblin": {
   "gain": 1.6142,
   "m": -19.5,
   "target": -19.5,
   "peak": -10.8
  },
  "vox_goblin_die": {
   "gain": 1.153,
   "m": -18.5,
   "target": -18.5,
   "peak": -10.8
  },
  "vox_human": {
   "gain": 1.2454,
   "m": -19.5,
   "target": -19.5,
   "peak": -9.5
  },
  "vox_human_die": {
   "gain": 1.0979,
   "m": -18.5,
   "target": -18.5,
   "peak": -10.7
  },
  "vox_kobold": {
   "gain": 1,
   "m": -19.2,
   "target": -19.5,
   "peak": -9.6
  },
  "vox_kobold_die": {
   "gain": 0.8798,
   "m": -18.5,
   "target": -18.5,
   "peak": -10.4
  },
  "vox_lizard": {
   "gain": 0.923,
   "m": -19.5,
   "target": -19.5,
   "peak": -9.5
  },
  "vox_lizard_die": {
   "gain": 0.6446,
   "m": -18.5,
   "target": -18.5,
   "peak": -13.4
  },
  "vox_ogre": {
   "gain": 0.4121,
   "m": -16.3,
   "target": -16.5,
   "peak": -12.1
  },
  "vox_ogre_die": {
   "gain": 0.3919,
   "m": -16.4,
   "target": -16.5,
   "peak": -10.6
  },
  "vox_orc": {
   "gain": 0.6479,
   "m": -19.5,
   "target": -19.5,
   "peak": -15.4
  },
  "vox_orc_die": {
   "gain": 0.6825,
   "m": -18.5,
   "target": -18.5,
   "peak": -15.1
  },
  "vox_party": {
   "gain": 1.8696,
   "m": -19.5,
   "target": -19.5,
   "peak": -8.4
  },
  "vox_party_die": {
   "gain": 1.258,
   "m": -18.5,
   "target": -18.5,
   "peak": -9.7
  },
  "vox_rat": {
   "gain": 5.3495,
   "m": -21,
   "target": -21,
   "peak": -12.9
  },
  "vox_rat_die": {
   "gain": 1.6327,
   "m": -18.5,
   "target": -18.5,
   "peak": -9.3
  },
  "vox_skeleton": {
   "gain": 1.6957,
   "m": -19.6,
   "target": -19.5,
   "peak": -3.8
  },
  "vox_skeleton_die": {
   "gain": 2.157,
   "m": -18.5,
   "target": -18.5,
   "peak": -7.6
  },
  "vox_spider": {
   "gain": 1.0632,
   "m": -19.5,
   "target": -19.5,
   "peak": -14.1
  },
  "vox_spider_die": {
   "gain": 9.0816,
   "m": -19.3,
   "target": -18.5,
   "peak": -2.2
  },
  "vox_troll": {
   "gain": 0.3864,
   "m": -16.4,
   "target": -16.5,
   "peak": -12.6
  },
  "vox_troll_die": {
   "gain": 0.3593,
   "m": -16.3,
   "target": -16.5,
   "peak": -10.3
  },
  "vox_wolf": {
   "gain": 0.575,
   "m": -19.5,
   "target": -19.5,
   "peak": -15.4
  },
  "vox_wolf_die": {
   "gain": 1,
   "m": -18.4,
   "target": -18.5,
   "peak": -9.8
  },
  "vox_zombie": {
   "gain": 1,
   "m": -19.3,
   "target": -19.5,
   "peak": -11.4
  },
  "vox_zombie_die": {
   "gain": 1.3054,
   "m": -18.5,
   "target": -18.5,
   "peak": -9.7
  },
  "walk": {
   "gain": 5.5402,
   "m": -26.1,
   "target": -26,
   "peak": -10.1
  }
 }
};
