/**
 * The standard screenshot gallery. Each entry exists in BOTH the homage
 * (shots/<name>.png via shotall.mjs) and the 1988 reference
 * (reference/<name>.png via refshot.mjs) for blind side-by-side comparison.
 * Keep query strings deterministic (seed + freeze).
 */
export const GALLERY = [
  { name: 'title', query: 'scene=title&t=6&seed=1' },
  { name: 'mainmenu', query: 'scene=title&view=menu&t=6&seed=1' },
  { name: 'settings', query: 'scene=title&view=settings&tab=graphics&t=6&seed=1' },
  { name: 'title_controls', query: 'scene=title&view=settings&tab=controls&t=6&seed=1' },
  { name: 'title_credits', query: 'scene=title&view=credits&t=9&seed=1' },
  { name: 'intro', query: 'scene=title&view=intro&t=13.5&seed=1' },
  { name: 'title_council', query: 'scene=title&view=intro&t=29&seed=1' },
  { name: 'title_chamber', query: 'scene=title&view=intro&t=37&seed=1' },
  { name: 'title_classic', query: 'scene=title&t=6&seed=1&classic=1' },
  { name: 'create', query: 'scene=create&step=stats&t=2&seed=1' },
  { name: 'create_party', query: 'scene=create&party=default&t=2&seed=1' },
  { name: 'create_portrait', query: 'scene=create&step=portrait&t=2&seed=1' },
  { name: 'create_party_720', query: 'scene=create&party=default&t=2&seed=1', w: 1280, h: 720 },
  { name: 'create_dwarf', query: 'scene=create&step=portrait&race=dwarf&gender=female&cls=fighter/thief&t=2&seed=1' },
  { name: 'explore', query: 'scene=explore&map=phlan_slums&x=7&y=11&dir=N&hour=10&t=2&seed=1' },
  { name: 'explore_door', query: 'scene=explore&map=phlan_slums&x=8&y=11&dir=S&hour=10&t=2&seed=1' },
  { name: 'explore_night', query: 'scene=explore&map=phlan_slums&x=1&y=14&dir=E&hour=22&t=2&seed=1' },
  { name: 'explore_dusk', query: 'scene=explore&map=phlan_slums&x=4&y=5&dir=E&hour=18.2&t=2&seed=1' },
  { name: 'explore_ruins', query: 'scene=explore&map=phlan_slums&x=4&y=5&dir=E&hour=16.5&tileset=ruins&t=2&seed=1' },
  { name: 'explore_dungeon', query: 'scene=explore&map=demo_dungeon&x=3&y=7&dir=E&t=2&seed=1', refQuery: 'scene=explore&map=valjevo_castle&x=7&y=14&dir=N&t=2&seed=1' },
  { name: 'explore_interior', query: 'scene=explore&map=demo_interior&x=2&y=1&dir=W&hour=11&t=2&seed=1', refQuery: 'scene=explore&map=mendors_library&x=7&y=12&dir=N&hour=11&t=2&seed=1' },
  { name: 'explore_warrens', query: 'scene=explore&map=kutos_warrens&x=7&y=13&dir=N&t=2&seed=1' },
  { name: 'explore_harbour', query: 'scene=explore&map=phlan_civilized&x=4&y=14&dir=S&hour=17.3&t=2&seed=1' },
  { name: 'explore_morning', query: 'scene=explore&map=phlan_slums&x=5&y=10&dir=E&hour=7.3&t=2&seed=1' },
  { name: 'explore_bane', query: 'scene=explore&map=temple_bane&x=7&y=15&dir=N&t=2&seed=1' },
  { name: 'explore_bane_altar', query: 'scene=explore&map=temple_bane&x=7&y=5&dir=N&t=2&seed=1' },
  { name: 'combat', query: 'scene=combat&encounter=kobolds_1&t=2&seed=1&hover=auto' },
  { name: 'combat_spell', query: 'scene=combat&encounter=orcs_1&party=veterans&demo=fireball&map=phlan_slums&x=4&y=4&t=0.75&seed=1' },
  { name: 'combat_melee', query: 'scene=combat&encounter=orcs_1&demo=melee&t=0.46&seed=1&yaw=0.3' },
  { name: 'combat_night', query: 'scene=combat&encounter=skeletons_1&hour=22&t=2&seed=1' },
  { name: 'combat_cloud', query: 'scene=combat&encounter=kobolds_1&demo=cloud&t=1.3&seed=1' },
  { name: 'combat_surprise', query: 'scene=combat&encounter=orcs_1&surprise=party&t=2&seed=1' },
  { name: 'combat_tyranthraxus', query: 'scene=combat&encounter=pool_tyranthraxus&party=veterans&map=pool_pyramid&x=7&y=6&t=2&seed=1' },
  { name: 'combat_target', query: 'scene=combat&encounter=kobolds_1&demo=target&t=2&seed=1' },
  { name: 'combat_turn', query: 'scene=combat&encounter=orcs_1&demo=banner&t=0.6&seed=1' },
  { name: 'automap', query: 'scene=automap&map=phlan_slums&x=7&y=11&dir=N&explored=demo&t=1&seed=1' },
  { name: 'automap_zoom', query: 'scene=automap&map=phlan_slums&x=7&y=11&dir=N&explored=demo&zoom=2.6&t=1&seed=1' },
  { name: 'automap_diorama', query: 'scene=automap&map=phlan_slums&x=7&y=11&dir=N&explored=demo&mode=diorama&t=1&seed=1' },
  { name: 'worldmap', ref: 'automap', query: 'scene=automap&view=world&map=phlan_slums&x=7&y=11&dir=N&explored=demo&t=1&seed=1' },
  { name: 'camp', query: 'scene=camp&hour=21.5&t=2&seed=1' },
  { name: 'camp_rest', query: 'scene=camp&hour=2&sleep=1&t=2&seed=1' },
  { name: 'charsheet', query: 'scene=camp&panel=view&member=0&hour=21.5&t=2&seed=1' },
  { name: 'inventory', query: 'scene=camp&panel=items&member=0&hour=21.5&t=2&seed=1' },
  { name: 'memorize', query: 'scene=camp&panel=magic&member=1&hour=21.5&t=2&seed=1' },
  { name: 'charsheet_thief', query: 'scene=camp&panel=view&member=4&hour=21.5&t=2&seed=1' },
  { name: 'dialogue', query: 'scene=dialogue&encounter=kobolds_1&t=1&seed=1' },
  { name: 'dialogue_npc', query: 'scene=dialogue&script=ferran&t=2&seed=1' },
  { name: 'dialogue_ghost', ref: 'dialogue', query: 'scene=dialogue&script=ferran&node=speak&t=2&seed=1' },
  { name: 'dialogue_hostile', ref: 'dialogue', query: 'scene=dialogue&encounter=kobolds_1&beat=hostile&t=1&seed=1' },
  { name: 'dialogue_flee', ref: 'dialogue', query: 'scene=dialogue&encounter=kobolds_1&beat=flee&t=1&seed=1' },
  { name: 'travel_boat', ref: 'dialogue', query: 'scene=dialogue&script=go_civ_sokol&t=2&seed=1' },
  { name: 'cityhall', ref: 'dialogue', query: 'scene=dialogue&script=city_hall&node=commissions&flags=met_clerk,slums_cleared&quests=clear_slums:done,sokol_keep:active&t=2&seed=1' },
  { name: 'journal', ref: 'dialogue', query: 'scene=dialogue&view=journal&journal=1,2,3,4,5,6,7,8,13,21&entry=7&t=2&seed=1' },
  { name: 'shop', query: 'scene=shop&shop=phlan_armory&item=bandedMail&t=1&seed=1' },
  { name: 'shop_sell', ref: 'shop', query: 'scene=shop&shop=phlan_armory&tab=sell&t=1&seed=1' },
  { name: 'temple', ref: 'shop', query: 'scene=shop&shop=temple_tyr&party=battered&t=1&seed=1' },
  { name: 'shop_tavern', query: 'scene=shop&shop=tavern_tankard&t=1&seed=1' },
  { name: 'shop_training', query: 'scene=shop&shop=training_hall&t=1&seed=1' },
  { name: 'temple_sune', ref: 'shop', query: 'scene=shop&shop=temple_sune&party=battered&t=1&seed=1' },
];
