import { ensureServer } from './lib/server.mjs';
import { launch } from './lib/browser.mjs';
const OUT = process.env.OUT;
const srv = await ensureServer({ port: 5350 });
const browser = await launch();
const page = await browser.newPage({ viewport: { width: 1280, height: 720 } });
await page.goto(`${srv.base}?scene=explore&map=phlan_slums&x=7&y=11&dir=N&hour=10&seed=1&classic=1`, { waitUntil: 'load' });
await page.waitForFunction(() => window.__READY === true, null, { timeout: 180000 });
await page.waitForTimeout(1500); if (process.env.P) await page.evaluate((p) => Object.assign(window.__GAME.render.lineArt.params, JSON.parse(p)), process.env.P); await page.waitForTimeout(500);
await page.screenshot({ path: `${OUT}/stab_a.png`, timeout: 240000 });
await page.waitForTimeout(700);
await page.screenshot({ path: `${OUT}/stab_b.png`, timeout: 240000 });
await browser.close(); await srv.close();
